<!DOCTYPE html>
<html>
  <title>
    Public Wifi Hotspots
  </title>

<head>
  <link href="include/style.css" rel="stylesheet" type="text/css" />
  <script type ="text/javascript" src="include/project.js"></script>
</head>


<div id="header">
  <h1> Public Wi-Fi Hotspots </h1>
</div>

<div id="parent">



  <div id="nav">

    <ul>
      <li><a href="index.php">Home</a></li>
      <li><a href="search.php">Search</a></li>
      <li><a href="reviews.php">Reviews</a></li>
      <li><a href="REGISTRATION.php">Register</a></li>
      <!-- <li><a href="user_log_in_homepage.php">Login</a></li> -->
    </ul>
  </div>

</div>
</div>
 <div id="footer">
   <p> Queensland University of Technology </p>

</div>
 </html>
